export default function TermsPage() {
  return (
    <>
      <h1 className="text-3xl md:text-4xl font-semibold mb-4">Terms of Service</h1>
      <p>Effective Date: December 4, 2025
Last Updated: December 4, 2025
Website: https://www.terratraks.com

Entity: TerraTraks

1. Acceptance of Terms

By accessing or using TerraTraks (“the Service”), you agree to these Terms of Service (“Terms”). If you do not agree, do not use this website.

2. Description of Service

TerraTraks provides AI-generated and user-edited travel itineraries, national park information, suggested hikes, routes, distances, driving times, lodging suggestions, and related travel-planning resources. TerraTraks does not guarantee accuracy and is not responsible for park closures, weather changes, road conditions, or trail safety.

3. Eligibility

Users must be at least 18 years old or have parental consent.

4. Accounts & Security

You must provide accurate registration information. You are responsible for maintaining the confidentiality of your account credentials.

5. Payments & Subscriptions

Paid plans are processed through Stripe. Prices are subject to change. No refunds are guaranteed unless required by law.

6. Affiliate Relationships

TerraTraks may earn commissions from third parties, including but not limited to AllTrails, Amazon, VRBO, Airbnb, Booking.com, outdoor gear retailers, and travel vendors. These relationships do not influence recommendations.

7. No Professional Advice

Information provided by TerraTraks, including itinerary suggestions, hike difficulty, and estimated durations, is not professional advice. Users assume all risk when acting on information found on this website.

8. User Conduct

You may not:

Scrape content

Copy or distribute our content without permission

Use TerraTraks for unlawful purposes

Attempt to access backend systems or APIs without authorization

9. Intellectual Property

All text, images, features, and branding are the property of TerraTraks or licensed partners. NPS images remain property of the U.S. National Park Service where used under permitted guidelines.

10. AI-Generated Content

Itineraries and travel suggestions may be generated by AI. Content may contain inaccuracies, outdated information, or subjective assessments.

11. Limitation of Liability

To the fullest extent permitted by law, TerraTraks is not liable for:

Injury, illness, or death during hikes or trips

Incorrect park data, closures, permits, conditions, or directions

Weather, wildlife encounters, altitude sickness, or natural disasters

Issues arising from third-party vendors or bookings

12. Termination

We may suspend accounts at any time for abuse or policy violations.

13. Governing Law

These Terms are governed by the laws of the United States and the user’s state of residence.</p>
    </>
  );
}

